######################################################################
# Automatically generated by qmake (2.01a) Do. Mai 17 16:12:09 2018
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . \
              src \
              3rdparty/JsonSettingsQML \
              3rdparty/SortFilterProxyModel \
              3rdparty/qnanopainter/libqnanopainter \
              3rdparty/SortFilterProxyModel/tests \
              3rdparty/qnanopainter/examples/gallery \
              3rdparty/qnanopainter/examples/helloworld \
              3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo \
              3rdparty/qnanopainter/libqnanopainter/nanovg \
              3rdparty/qnanopainter/libqnanopainter/private \
              3rdparty/qnanopainter/examples/gallery/mouse_events \
              3rdparty/qnanopainter/examples/gallery/painting \
              3rdparty/qnanopainter/examples/gallery/qnanopainter_features \
              3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src \
              3rdparty/qnanopainter/examples/gallery/mouse_events/src \
              3rdparty/qnanopainter/examples/gallery/painting/src \
              3rdparty/qnanopainter/examples/gallery/qnanopainter_features/src
INCLUDEPATH += . \
               src \
               3rdparty/qnanopainter/libqnanopainter \
               3rdparty/qnanopainter/libqnanopainter/nanovg \
               3rdparty/qnanopainter/libqnanopainter/private \
               3rdparty/JsonSettingsQML \
               3rdparty/SortFilterProxyModel \
               3rdparty/SortFilterProxyModel/tests \
               3rdparty/qnanopainter/examples/gallery/qnanopainter_features/src \
               3rdparty/qnanopainter/examples/gallery/mouse_events/src \
               3rdparty/qnanopainter/examples/gallery/painting/src \
               3rdparty/qnanopainter/examples/helloworld \
               3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src

# Input
HEADERS += src/barchart.h \
           src/bardata.h \
           src/barscaledraw.h \
           src/cbar.h \
           src/fftbarchart.h \
           src/fpscounter.h \
           src/gluelogicpropertymap.h \
           src/hpwbarchart.h \
           src/phasordiagram.h \
           src/qmlfileio.h \
           src/sidescaledraw.h \
           src/zeragluelogic.h \
           src/zeratranslation.h \
           3rdparty/JsonSettingsQML/jsonglobalsettings.h \
           3rdparty/JsonSettingsQML/jsonsettings_plugin.h \
           3rdparty/JsonSettingsQML/jsonsettingsfile.h \
           3rdparty/SortFilterProxyModel/filter.h \
           3rdparty/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
           3rdparty/SortFilterProxyModel/sorter.h \
           3rdparty/qnanopainter/libqnanopainter/qnanoboxgradient.h \
           3rdparty/qnanopainter/libqnanopainter/qnanocolor.h \
           3rdparty/qnanopainter/libqnanopainter/qnanofont.h \
           3rdparty/qnanopainter/libqnanopainter/qnanoimage.h \
           3rdparty/qnanopainter/libqnanopainter/qnanoimagepattern.h \
           3rdparty/qnanopainter/libqnanopainter/qnanolineargradient.h \
           3rdparty/qnanopainter/libqnanopainter/qnanopainter.h \
           3rdparty/qnanopainter/libqnanopainter/qnanoquickitem.h \
           3rdparty/qnanopainter/libqnanopainter/qnanoquickitempainter.h \
           3rdparty/qnanopainter/libqnanopainter/qnanoradialgradient.h \
           3rdparty/SortFilterProxyModel/tests/indexsorter.h \
           3rdparty/qnanopainter/examples/helloworld/helloitem.h \
           3rdparty/qnanopainter/libqnanopainter/nanovg/fontstash.h \
           3rdparty/qnanopainter/libqnanopainter/nanovg/nanovg.h \
           3rdparty/qnanopainter/libqnanopainter/nanovg/nanovg_gl.h \
           3rdparty/qnanopainter/libqnanopainter/nanovg/nanovg_gl_utils.h \
           3rdparty/qnanopainter/libqnanopainter/nanovg/stb_image.h \
           3rdparty/qnanopainter/libqnanopainter/nanovg/stb_truetype.h \
           3rdparty/qnanopainter/libqnanopainter/private/qnanobrush.h \
           3rdparty/qnanopainter/libqnanopainter/private/qnanodataelement.h \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqnanoitem.h \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqnanoitempainter.h \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqpitem.h \
           3rdparty/qnanopainter/examples/gallery/mouse_events/src/eventitem.h \
           3rdparty/qnanopainter/examples/gallery/mouse_events/src/eventitempainter.h \
           3rdparty/qnanopainter/examples/gallery/painting/src/paintingitem.h \
           3rdparty/qnanopainter/examples/gallery/painting/src/paintingitempainter.h \
           3rdparty/qnanopainter/examples/gallery/qnanopainter_features/src/galleryitem.h \
           3rdparty/qnanopainter/examples/gallery/qnanopainter_features/src/galleryitempainter.h
SOURCES += src/barchart.cpp \
           src/bardata.cpp \
           src/barscaledraw.cpp \
           src/cbar.cpp \
           src/fftbarchart.cpp \
           src/fpscounter.cpp \
           src/gluelogicpropertymap.cpp \
           src/hpwbarchart.cpp \
           src/main.cpp \
           src/phasordiagram.cpp \
           src/qmlfileio.cpp \
           src/sidescaledraw.cpp \
           src/zeragluelogic.cpp \
           src/zeratranslation.cpp \
           3rdparty/JsonSettingsQML/jsonglobalsettings.cpp \
           3rdparty/JsonSettingsQML/jsonsettings_plugin.cpp \
           3rdparty/JsonSettingsQML/jsonsettingsfile.cpp \
           3rdparty/SortFilterProxyModel/filter.cpp \
           3rdparty/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp \
           3rdparty/SortFilterProxyModel/sorter.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanoboxgradient.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanocolor.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanofont.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanoimage.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanoimagepattern.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanolineargradient.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanopainter.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanoquickitem.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanoquickitempainter.cpp \
           3rdparty/qnanopainter/libqnanopainter/qnanoradialgradient.cpp \
           3rdparty/SortFilterProxyModel/tests/indexsorter.cpp \
           3rdparty/SortFilterProxyModel/tests/tst_sortfilterproxymodel.cpp \
           3rdparty/qnanopainter/examples/gallery/main.cpp \
           3rdparty/qnanopainter/examples/helloworld/main.cpp \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/main.cpp \
           3rdparty/qnanopainter/libqnanopainter/nanovg/nanovg.c \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqnanoitem.cpp \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqnanoitempainter.cpp \
           3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/src/demoqpitem.cpp \
           3rdparty/qnanopainter/examples/gallery/mouse_events/src/eventitem.cpp \
           3rdparty/qnanopainter/examples/gallery/mouse_events/src/eventitempainter.cpp \
           3rdparty/qnanopainter/examples/gallery/painting/src/paintingitem.cpp \
           3rdparty/qnanopainter/examples/gallery/painting/src/paintingitempainter.cpp \
           3rdparty/qnanopainter/examples/gallery/qnanopainter_features/src/galleryitem.cpp \
           3rdparty/qnanopainter/examples/gallery/qnanopainter_features/src/galleryitempainter.cpp
RESOURCES += data.qrc \
             qml.qrc \
             3rdparty/qnanopainter/libqnanopainter/libqnanopainterdata.qrc \
             3rdparty/qnanopainter/examples/gallery/qml.qrc \
             3rdparty/qnanopainter/examples/helloworld/qml.qrc \
             3rdparty/qnanopainter/examples/qnanopainter_vs_qpainter_demo/qml.qrc \
             3rdparty/qnanopainter/examples/gallery/mouse_events/mouse_events.qrc \
             3rdparty/qnanopainter/examples/gallery/painting/painting.qrc \
             3rdparty/qnanopainter/examples/gallery/qnanopainter_features/qnanopainter_features.qrc
