on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
    	MODULENAME: ${{github.repository}}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    steps:
      
      - uses: convictional/trigger-workflow-and-wait@v1.4.0
        with:
          owner: ZeraGmbH
          repo: zera-metaproject
          workflow_file_name: updateSubmodule.yml
          inputs: '{"submodule" : "${{ env.MODULENAME }}"}'  

